---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/guesses":
    post:
      summary: Creates a new guess
      tags:
      - Guesses
      parameters: []
      responses:
        '201':
          description: guess recorded
        '400':
          description: guess invalid
        '404':
          description: treasure hunt not found
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                answer:
                  type: string
                  required: true
                email:
                  type: string
                  required: true
                treasure_id:
                  type: integer
                  required: true
              required:
              - answer
              - email
              - treasure_id
  "/treasures":
    post:
      summary: Creates a new treasure hunt
      tags:
      - Treasure Hunts
      parameters: []
      responses:
        '201':
          description: treasure hunt created
        '400':
          description: treasure hunt invalid
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                answer:
                  type: string
                  required: true
              required:
              - answer
  "/treasures/{id}/winners":
    get:
      summary: Fetch the current winning guesses for the treasure hunt
      tags:
      - Treasure Hunts
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      - name: page
        in: query
        required: false
        schema:
          type: string
      - name: per_page
        in: query
        required: false
        schema:
          type: string
      - name: order
        in: query
        required: false
        schema:
          type: string
      responses:
        '200':
          description: returns a list of winners
        '400':
          description: invalid request
        '404':
          description: treasure hunt not found
  "/treasures/{id}/deactivate":
    put:
      summary: Deactivates a treasure hunt, stopping any further guesses from being
        made
      tags:
      - Treasure Hunts
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: returns the deactivated treasure hunt
        '404':
          description: treasure hunt not found
  "/treasures/{id}":
    delete:
      summary: Deletes a treasure hunt
      tags:
      - Treasure Hunts
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '204':
          description: no content response, confirms delete
        '404':
          description: treasure hunt not found
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
